# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Barter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(757, 184)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 10, 611, 167))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.StoreGoodsNameBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.StoreGoodsNameBox.setObjectName("StoreGoodsNameBox")
        self.gridLayout.addWidget(self.StoreGoodsNameBox, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.ClientGoodsNameBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.ClientGoodsNameBox.setObjectName("ClientGoodsNameBox")
        self.gridLayout.addWidget(self.ClientGoodsNameBox, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.ClientCountSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.ClientCountSpinBox.setMinimum(1)
        self.ClientCountSpinBox.setObjectName("ClientCountSpinBox")
        self.gridLayout.addWidget(self.ClientCountSpinBox, 1, 1, 1, 1)
        self.StoreCountSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.StoreCountSpinBox.setMinimum(1)
        self.StoreCountSpinBox.setObjectName("StoreCountSpinBox")
        self.gridLayout.addWidget(self.StoreCountSpinBox, 3, 1, 1, 1)
        self.ClientPrice = QtWidgets.QLabel(self.formLayoutWidget)
        self.ClientPrice.setObjectName("ClientPrice")
        self.gridLayout.addWidget(self.ClientPrice, 1, 2, 1, 1)
        self.StorePrice = QtWidgets.QLabel(self.formLayoutWidget)
        self.StorePrice.setObjectName("StorePrice")
        self.gridLayout.addWidget(self.StorePrice, 3, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.countOnStore = QtWidgets.QLabel(self.formLayoutWidget)
        self.countOnStore.setObjectName("countOnStore")
        self.gridLayout.addWidget(self.countOnStore, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.okBtn = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okBtn.sizePolicy().hasHeightForWidth())
        self.okBtn.setSizePolicy(sizePolicy)
        self.okBtn.setObjectName("okBtn")
        self.gridLayout.addWidget(self.okBtn, 0, 3, 2, 1)
        self.cancelBtn = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelBtn.sizePolicy().hasHeightForWidth())
        self.cancelBtn.setSizePolicy(sizePolicy)
        self.cancelBtn.setObjectName("cancelBtn")
        self.gridLayout.addWidget(self.cancelBtn, 3, 3, 2, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "От Клиента"))
        self.label_2.setText(_translate("Dialog", "От Склада"))
        self.label_4.setText(_translate("Dialog", "Цена"))
        self.label_3.setText(_translate("Dialog", "Цена"))
        self.ClientPrice.setText(_translate("Dialog", "TextLabel"))
        self.StorePrice.setText(_translate("Dialog", "TextLabel"))
        self.label_7.setText(_translate("Dialog", "Количество"))
        self.label_8.setText(_translate("Dialog", "Количество"))
        self.countOnStore.setText(_translate("Dialog", "0"))
        self.label_5.setText(_translate("Dialog", "На складе сейчас:"))
        self.okBtn.setText(_translate("Dialog", "Подтвердить"))
        self.cancelBtn.setText(_translate("Dialog", "Отмена"))

